### PR TITLE
add py39 to the build matrix

### PR DESCRIPTION
**Pull request by mariusvniekerk**

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by jakirkham** [comment]
Restarting failed jobs to see if this was just a fluke based on when `python` `3.9` packages were published. Thinking this as macOS had no issues, but Linux `x86_64` and Windows did.

**Comment by mbargull** [comment]
This needs to be restarted again in a couple of minutes after the CDN sync has applied https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/90.

**Comment by jakirkham** [comment]
Sounds like we may be pausing the migration ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/844 ).

**Comment by CJ-Wright** [comment]
Yes, That PR was actually because I messed up. But without this the PRs are not passing on CI

**Comment by mariusvniekerk** [comment]
Seems we had two osx builds with the same build number for python around, marked the older one as broken.

**Comment by mbargull** [comment]
Oh what? So did the builds on the `prerelease` branch get uploaded to the `main` label?

**Comment by mbargull** [comment]
https://anaconda.org/conda-forge/python/3.9.0/download/win-64/python-3.9.0-h60c2a47_0_cpython.tar.bz2 and https://anaconda.org/conda-forge/python/3.9.0/download/linux-64/python-3.9.0-h852b56e_0_cpython.tar.bz2 are old ones, too, probably from `prerelease` branch.
We should mark them `broken` and do another build (i.e., build number bump).

**Comment by mariusvniekerk** [comment]
there is a pr in to buimp the build number https://github.com/conda-forge/python-feedstock/pull/397

**Pull request merged**
