### PR TITLE
Use build number in string

### PR DESCRIPTION
**Pull request by isuruf**
cc @mbargull, @conda-forge/python 

@mbargull, raised the question that we might need to change this package, so adding a build number to the string might be needed.

What do you think?

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
The other alternative is to change the version, but I think that would be confusing to many.

**Comment by isuruf** [comment]
Other option is to change the version to something like 0.1, but that would be confusing to many users.

**Comment by isuruf** [comment]
Ping

**Review by ocefpaf — APPROVED** [review]

**Comment by jakirkham** [comment]
Yeah I think this makes sense, Isuru. My guess is people were deferring to you as you have a clear idea of how this is all working 🙂

**Pull request merged**
